/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Javier Tareas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbOperacion = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        txtNumeros3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtComplejo3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        txtDenominador1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtDenominador2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNumeros1 = new javax.swing.JTextField();
        txtComplejo1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNumeros2 = new javax.swing.JTextField();
        txtComplejo2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbOperacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 20));

        txtNumeros3.setEditable(false);
        jPanel1.add(txtNumeros3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 40, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 40, 10));

        txtComplejo3.setEditable(false);
        jPanel1.add(txtComplejo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 40, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cmdCalcular)
                .addGap(18, 18, 18)
                .addComponent(cmdLimpiar)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCalcular)
                    .addComponent(cmdLimpiar)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 60));

        txtDenominador1.setEditable(false);
        jPanel1.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 40, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 40, 10));

        txtDenominador2.setEditable(false);
        jPanel1.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("+");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 20, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText(" i");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 10, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Z1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeros1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(txtNumeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));

        txtComplejo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(txtComplejo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 40, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("+");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 20, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" i");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText(" (");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText(")");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 10, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Z2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeros2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtNumeros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, -1));

        txtComplejo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtComplejo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplejo2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtComplejo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 40, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText(" (");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText(")");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 10, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText(" i");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("+");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 20, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 170, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int op, n1, n2, n3=0, d1, d2, d3=0;
        Complejos f1, f2, f3 = null;
        int sw = 1;
        txtNumeros3.setText("");
        txtComplejo3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");

        if (txtNumeros1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la parte real de Z1", "Error", 2);
            txtNumeros1.requestFocusInWindow();
            sw = 0;
        } else if (txtComplejo1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la parte imaginaria de Z1", "Error", 2);
            txtComplejo1.requestFocusInWindow();
            sw = 0;
        } else if (txtNumeros2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la parte real de Z2", "Error", 2);
            txtNumeros2.requestFocusInWindow();
            sw = 0;
        } else if (txtComplejo2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la parte imaginaria de Z2", "Error", 2);
            txtComplejo2.requestFocusInWindow();
            sw = 0;
        } else {
            try {
                n1 = Integer.parseInt(txtNumeros1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la parte real de Z1 correctamente", "Error", 2);
                txtNumeros1.requestFocusInWindow();
                txtNumeros1.selectAll();
                sw = 0;
            }
            try {
                d1 = Integer.parseInt(txtComplejo1.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la parte imaginaria de Z1 correctamente", "Error", 2);
                txtComplejo1.requestFocusInWindow();
                txtComplejo1.selectAll();
                sw = 0;
            }
            try {
                n2 = Integer.parseInt(txtNumeros2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la parte real de Z2 correctamente", "Error", 2);
                txtNumeros2.requestFocusInWindow();
                txtNumeros2.selectAll();
                sw = 0;
            }
            try {
                d2 = Integer.parseInt(txtComplejo2.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese la parte imaginaria de Z2 correctamente", "Error", 2);
                txtComplejo2.requestFocusInWindow();
                txtComplejo2.selectAll();
                sw = 0;
            }
        }
        if (sw == 1) {
            n1 = Integer.parseInt(txtNumeros1.getText());
            d1 = Integer.parseInt(txtComplejo1.getText());
            n2 = Integer.parseInt(txtNumeros2.getText());
            d2 = Integer.parseInt(txtComplejo2.getText());
            op = cmbOperacion.getSelectedIndex();
            try {
                f1 = new Complejos(n1, d1, n3, d3);
                f2 = new Complejos(n2, d2, n3, d3);

                switch (op) {
                    case 0:
                    f3 = f1.suma(f2);
                    break;
                    case 1:
                    f3 = f1.resta(f2);
                    break;
                    case 2:
                    f3 = f1.multiplicacion(f2);
                    break;
                    case 3:
                    f3 = f1.division(f2);
                    break;
                }
                txtNumeros3.setText("" + f3.getNumeros());
                txtComplejo3.setText("" + f3.getComplejos());
                txtDenominador1.setText("" + f3.getDenominador_uno());
                txtDenominador2.setText("" + f3.getDenominador_dos());
            } finally {
          }
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNumeros1.setText("");
        txtNumeros2.setText("");
        txtNumeros3.setText("");
        txtComplejo1.setText("");
        txtComplejo2.setText("");
        txtComplejo3.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtNumeros1.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);

    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtComplejo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplejo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplejo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtComplejo1;
    private javax.swing.JTextField txtComplejo2;
    private javax.swing.JTextField txtComplejo3;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtNumeros1;
    private javax.swing.JTextField txtNumeros2;
    private javax.swing.JTextField txtNumeros3;
    // End of variables declaration//GEN-END:variables
}
